version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - 8081:8081
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "start"]

  frontend: 
    build: ./client
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
